services:

  gpsd-exporter:
    image: ghcr.io/brendanbank/gpsd-prometheus-exporter:latest
    container_name: gpsd-exporter
    ports:
      - "${EXPORTER_PORT:-9015}:9015"
    environment:
      - GPSD_HOST=${GPSD_HOST:-host.docker.internal}
      - GPSD_PORT=${GPSD_PORT:-2947}
      - GEOPOINT_LON=${GEOPOINT_LON:-38.897809878}
      - GEOPOINT_LAT=${GEOPOINT_LAT:--77.036551259}
      - PPS_BUCKET_SIZE=${PPS_BUCKET_SIZE:-50000}
      - PPS_BUCKET_COUNT=${PPS_BUCKET_COUNT:-40}
      - PPS_TIME1=${PPS_TIME1}
      - GEO_BUCKET_SIZE=${GEO_BUCKET_SIZE:-0.5}
      - GEO_BUCKET_COUNT=${GEO_BUCKET_COUNT:-40}
      - EXPORTER_PORT=${EXPORTER_PORT:-9015}
      - DEBUG=${DEBUG:-0}
      - VERBOSE=${VERBOSE:-1}
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
    network_mode: host
    