version: "3"
services:

  gpsd-exporter:
    image: ghcr.io/ncareau/gpsd-prometheus-exporter:latest
    container_name: gpsd-exporter
    ports:
      - 9015:9015
    environment:
      - GPSD_HOST=host.docker.internal
      - GPSD_PORT=2947
      - GEOPOINT_LON=38.897809878
      - GEOPOINT_LAT=-77.036551259
      - PPS_BUCKET_SIZE=50000
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped